### ISSUE TITLE
Relatório

### ISSUE THREAD

**Issue by gustavoSutil** [HeitorAxe/Trabalho-Final-IA#4]
- [x] 3. Organizar um relatório em PDF apresentando os resultados do experimento.
   - [ ] - Comece o relatório com os dados do grupo e introduza o tema escolhido para as imagens selecionadas.
   - [x] - Inclua no cabeçalho/capa do relatório o link para o GitHub contendo o projeto Python com o código e as imagens utilizadas em sua resolução origina.
   - [x] - Apresente quadros comparativos com cada um dos conjuntos de imagens (7 imagens geradas mais a imagem original) parecido com o quadro de imagens abaixo (sugere-se agrupar as imagens em 2 linhas de 4 imagens ou 4 linhas com 2 imagens – o tamanho delas deve ser reduzido mantendo-se as proporções originais para caber nas páginas A4:
   - [x] - Apresente também uma tabela ou gráfico para cada conjunto de imagens apresentando as propriedades das imagens (resolução, tamanho e quantidade de cores).
   - [ ] - Descreva uma breve conclusão onde é analisado e comentado qual é a relação entre a redução de tamanho na imagem e a perda de informação (traduzida numericamente na de redução de cores únicas e também na percepção visual da imagem resultante).
   - [ ]  - Busque responder a seguinte questão de pesquisa usando os resultados dos experimentos realizados para basear a resposta: É possível usar o algoritmo k-médias para reduzir o tamanho de imagens com uma perda “inteligente” de informação que não ocasiona prejuízo visual considerável?

## Entrega e Prazos

A entrega do trabalho deverá ser realizada no SIGAA (um único arquivo PDF com o relatório) e disponibilizada no GitHub (projeto Python com o código e as imagens utilizadas em sua resolução original) até o dia indicado no SIGAA previsto para a apresentação do trabalho (apenas um dos integrantes da dupla necessita entregar o trabalho). Lembrem de deixar o projeto no GitHub com acesso público.

## Método de Avaliação

A avaliação do trabalho será dividida em duas etapas: avaliação do trabalho entregue no SIGAA/GitHub e a avaliação da apresentação. Será atribuída nota zero para ambas etapas caso o grupo não realize a apresentação para a turma.

A avaliação do trabalho de pesquisa prático será a mesma para todos os integrantes do grupo e considerará os seguintes itens:
- Adequação aos requisitos solicitados no trabalho.
- Organização e documentação do código (separação adequada do código em funções, nomes significativos para variáveis, estruturas e funções, comentários de código em partes importantes).
- Organização, clareza e completude dos resultados no relatório.

A avaliação da apresentação do trabalho será individual por integrante do grupo e considerará os seguintes itens:
- Criatividade, organização e preparo.
- Objetividade e clareza na fala e nos elementos auxiliares utilizados (slides, gráficos, imagens, outros).
- Adequação ao tempo definido, de no máximo 15min.

Será dado nota 0 (zero) para todos os estudantes que não entregarem o trabalho dentro do prazo esttipulado ou que plagiarem o trabalho em sua totalidade ou em considerável parte de um colega ou de fonte externa.

**Comment by gustavoSutil** [comment]
@HeitorAxe @Heitor Do Axé consegue mandar o link do DOCS? bb?

**Comment by HeitorAxe** [comment]
> @HeitorAxe @Heitor Do Axé consegue mandar o link do DOCS? bb?

https://docs.google.com/document/d/1TLfAyjAVhfkthkzlqsw2Kt2j4O2jHMn_Xzys_D9ALEk/edit?usp=sharing

**Comment by gustavoSutil** [comment]
@HeitorAxe consegue dar pull request nas alterações do relatório automático?
